version: "3.8"

services:
  # Browser container. Exposes ports for WebDriver (4444) and noVNC (7900).
  browser:
    image: seleniarm/standalone-chromium:latest
    shm_size: 2g
    ports:
      - "4444:4444"
      - "7900:7900"
    environment:
      # Password for the VNC/noVNC server (change it if you like)
      - SE_VNC_PASSWORD=secret

  # Container that runs the scraping script
  scraper:
    build: .
    depends_on:
      - browser
    environment:
      # Remote WebDriver address. Docker Compose resolves the `browser` service
      # name automatically.
      - BROWSER_URL=http://browser:4444/wd/hub